CYJ/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CYJ.Models;

namespace CYJ.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Admin()
        {

            return View();
        }
    
        public ActionResult Added()
        {
            return View();
        }
        public ActionResult Add()
        {
            return View();
        }
        public ActionResult ServiceDelivery()
        {
            return View();
        }

     
        public ActionResult CorpMemberExperience()
        {
            return View();
        }
        public ActionResult ExternalAffairs()
        {
            return View();
        }
        public ActionResult Revenue()
        {
            return View();
        }
        public ActionResult OpEx()
        {
            return View();
        }
        public ActionResult RAD()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetEvents()
        {
            using (cyjEntities1 dc = new cyjEntities1())
            {
                var events = dc.Calendars.ToList();
                return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
        [HttpPost]
        public JsonResult SaveEvent(Calendar e)
        {
            var status = false;
            using (cyjEntities1 dc = new cyjEntities1())
            {
                if (e.EventID > 0)
                {
                    //Update the event
                    var v = dc.Calendars.Where(a => a.EventID == e.EventID).FirstOrDefault();
                    if (v != null)
                    {
                        v.Subject = e.Subject;
                        v.Start = e.Start;
                        v.End = e.End;
                        v.Description = e.Description;
                        v.isFullDay = e.isFullDay;
                        v.ThemeColor = e.ThemeColor;
                    }
                }
                else
                {
                    dc.Calendars.Add(e);
                }
                dc.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (cyjEntities1 dc = new cyjEntities1())
            {
                var v = dc.Calendars.Where(a => a.EventID == eventID).FirstOrDefault();
                if (v != null)
                {
                    dc.Calendars.Remove(v);
                    dc.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }
    }
}

CYJ/Controllers/TEAMsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CYJ.Models;

namespace CYJ.Controllers
{
    [Authorize]
    public class TEAMsController : Controller
    {
        private cyjEntities db = new cyjEntities();

        // GET: TEAMs
        public ActionResult Index()
        {
            return View(db.TEAMs.ToList());
        }

        // GET: TEAMs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TEAM tEAM = db.TEAMs.Find(id);
            if (tEAM == null)
            {
                return HttpNotFound();
            }
            return View(tEAM);
        }

        // GET: TEAMs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TEAMs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "TeamID,TeamName")] TEAM tEAM)
        {
            if (ModelState.IsValid)
            {
                db.TEAMs.Add(tEAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tEAM);
        }

        // GET: TEAMs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TEAM tEAM = db.TEAMs.Find(id);
            if (tEAM == null)
            {
                return HttpNotFound();
            }
            return View(tEAM);
        }

        // POST: TEAMs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "TeamID,TeamName")] TEAM tEAM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tEAM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tEAM);
        }

        // GET: TEAMs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TEAM tEAM = db.TEAMs.Find(id);
            if (tEAM == null)
            {
                return HttpNotFound();
            }
            return View(tEAM);
        }

        // POST: TEAMs/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TEAM tEAM = db.TEAMs.Find(id);
            db.TEAMs.Remove(tEAM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CYJ/Views/Home/Access.cshtml
@model UNFDash.Models.ManageLoginsViewModel
@using Microsoft.Owin.Security
@{
    ViewBag.Title = "Manage your external logins";
    Layout = "~/Views/Shared/_dashboard.cshtml";
}
}

<h2>@ViewBag.Title.</h2>

<p class="text-success">@ViewBag.StatusMessage</p>
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {
        <div>
            <p>
                There are no external authentication services configured. See <a href="https://go.microsoft.com/fwlink/?LinkId=313242">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else
    {
        if (Model.CurrentLogins.Count > 0)
        {
            <h4>Registered Logins</h4>
            <table class="table">
                <tbody>
                    @foreach (var account in Model.CurrentLogins)
                    {
                        <tr>
                            <td>@account.LoginProvider</td>
                            <td>
                                @if (ViewBag.ShowRemoveButton)
                                {
                                    using (Html.BeginForm("RemoveLogin", "Manage"))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div>
                                            @Html.Hidden("loginProvider", account.LoginProvider)
                                            @Html.Hidden("providerKey", account.ProviderKey)
                                            <input type="submit" class="btn btn-default" value="Remove" title="Remove this @account.LoginProvider login from your account" />
                                        </div>
                                    }
                                }
                                else
                                {
                                    @: &nbsp;
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        if (Model.OtherLogins.Count > 0)
        {
            using (Html.BeginForm("LinkLogin", "Manage"))
            {
                @Html.AntiForgeryToken()
                <div id="socialLoginList">
                    <p>
                        @foreach (AuthenticationDescription p in Model.OtherLogins)
                        {
                            <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                        }
                    </p>
                </div>
            }
        }
    }
}

CYJ/Views/Home/Add.cshtml
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}


<body>
<div class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header" style="BACKGROUND-COLOR:#BCC65C">
                    <h4 class="title">ADD A NEW ITEM</h4>

                </div>
                <div class="card-content">

                    <center>
                        <div class="row">
                        <div class="col-md-4">
                            <div class="card card-pricing card-raised">
                                <div class="card-content">
                                    <div class="icons">
                                        <i class="material-icons" style="font-size: 100px; color:#bedde0">people</i>
                                    </div>
                                    <div></div>
                                    <input type="button" class="btn" style="background-color:#3EC2CF"value="ADD TEAM"  onclick="@("window.location.href='" + @Url.Action("Create", "TEAMs") + "'");" />
                        

                                </div>
                            </div>
                        </div>


                        <div class="col-md-4">
                            <div class="card card-pricing card-raised">
                                <div class="card-content">
                                    <div class="icons">
                                        <i class="material-icons"  style="font-size: 100px; color:#bedde0">work</i>
                                    </div>
                                    <input type="button" class="btn" style="background-color:#3EC2CF" value="ADD WORKSTREAM" onclick="@("window.location.href='" + @Url.Action("Create", "WORKSTREAMs") + "'");" />


                                </div>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="card card-pricing card-raised">
                                <div class="card-content">
                                    <div class="icons">
                                        <i class="material-icons"  style="font-size: 100px; color:#bedde0">label</i>
                                    </div>
                                    <input type="button" class="btn" style="background-color:#3EC2CF" value="ADD CATEGORY"  onclick="@("window.location.href='" + @Url.Action("Create", "CATEGORies") + "'");" />


                                </div>
                            </div>
                        </div>
                            </div>


                        <div class="row">
                            <div class="col-md-4">
                                <div class="card card-pricing card-raised">
                                    <div class="card-content">
                                        <div class="icons">
                                            <i class="material-icons"  style="font-size: 100px; color:#bedde0">label_outline</i>
                                        </div>
                                        <input type="button" class="btn" style="background-color:#3EC2CF" value="ADD SUBCATEGORY" onclick="@("window.location.href='" + @Url.Action("Create", "SUBCATEGORies") + "'");" />


                                    </div>
                                </div>
                            </div>


                            <div class="col-md-4">
                                <div class="card card-pricing card-raised">
                                    <div class="card-content">
                                        <div class="icons">
                                            <i class="material-icons"  style="font-size: 100px; color:#bedde0">date_range</i>
                                        </div>
                                        <input type="button" class="btn" style="background-color:#3EC2CF" value="ADD FISCAL YEAR"  onclick="@("window.location.href='" + @Url.Action("Create", "FISCALYEARs") + "'");" />


                                    </div>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="card card-pricing card-raised">
                                    <div class="card-content">
                                        <div class="icons">
                                            <i class="material-icons"  style="font-size: 100px; color:#bedde0">timer</i>
                                        </div>
                                        <input type="button"class="btn" style="background-color:#3EC2CF" value="ADD PERIOD" onclick="@("window.location.href='" + @Url.Action("Create", "QUARTEROPTIONs") + "'");" />

                            

                                    </div>
                                </div>
                            </div>

                        </div>



                    </center>
                </div>
            </div>
        </div>
    </div>
    </body>

CYJ/Views/Home/Added.cshtml
@{
    ViewBag.Title = "Added";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Your item was added successfully!</h2>

CYJ/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}
<!doctype html>


<div class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header" style="BACKGROUND-COLOR:#BCC65C">
                <h4 class="title">ADMIN</h4>

            </div>
            <div class="card-content">

                <center>

                    <div class="col-md-4">
                        <div class="card card-pricing card-raised">
                            <div class="card-content">
                                <div class="icons">
                                    <i class="material-icons" style="font-size: 100px; color:#bedde0">add_circle</i>
                                </div>
                                <input type="button" class="btn" style="background-color:#3EC2CF" value="ADD A NEW ITEM" Onclick="@("window.location.href='" + @Url.Action("Add", "Home") + "'");" />

                                <p class="card-description">Add a new team, workstream, goal category, etc.</p>
                              
                            </div>
                        </div>
                         </div>


                    <div class="col-md-4">
                        <div class="card card-pricing card-raised">
                            <div class="card-content">
                                <div class="icons">
                                    <i class="material-icons" style="font-size: 100px; color:#bedde0">update</i>
                                </div>
                                <input type="button" class="btn" style="background-color:#3EC2CF" value="UPDATE A GOAL" onclick="@("window.location.href='" + @Url.Action("Index", "GOALACTUALs") + "'");" />

                                <p class="card-description">Edit and delete current goal values and actuals.</p>

                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="card card-pricing card-raised">
                            <div class="card-content">
                                <div class="icons">
                                    <i class="material-icons"style="font-size: 100px; color:#bedde0">info</i>
                                </div>
                                <input type="button" class="btn" style="background-color:#3EC2CF" value="EDIT ABOUT" onclick="@("window.location.href='" + @Url.Action("Index", "ABOUTs") + "'");" />

                                <p class="card-description">Add a new post or edit an entry on the about page.</p>

                            </div>
                        </div>
                    </div>



                    <br /> <br /> <br /> <br /> <br />


                </center>
            </div>
        </div>
    </div>
</div>

CYJ/Views/Home/ServiceDelivery.cshtml
@{
    ViewBag.Title = "Service Delivery";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}